// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShortListMVC.Data;

#nullable disable

namespace ShortListMVC.Migrations.Post
{
    [DbContext(typeof(PostContext))]
    [Migration("20220314124138_SeedCategories")]
    partial class SeedCategories
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("ShortListMVC.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "dinner",
                            Name = "Kayıp",
                            Slug = "lost"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "home",
                            Name = "Evcil Hayvanlar",
                            Slug = "pets"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "tshirt",
                            Name = "Eleman Aranıyor",
                            Slug = "hiring"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "travel",
                            Name = "İkinci El",
                            Slug = "secondhand"
                        },
                        new
                        {
                            Id = 5,
                            Icon = "jobs",
                            Name = "Serbest Çalışanlar",
                            Slug = "hiring"
                        },
                        new
                        {
                            Id = 6,
                            Icon = "bullhorn",
                            Name = "Etkinlikler",
                            Slug = "hiring"
                        },
                        new
                        {
                            Id = 7,
                            Icon = "bolt",
                            Name = "Ev yapımı",
                            Slug = "handmade"
                        });
                });

            modelBuilder.Entity("ShortListMVC.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("ShortListMVC.Models.Post", b =>
                {
                    b.HasOne("ShortListMVC.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
